### ISSUE TITLE
Engine blades

### ISSUE THREAD

**Issue by rx4** [legoboyvdlp/787-9#20]
The engine blades do not look right. Same with the landing gear doors. They look like they are orange. I am using flightgear 2017.2.1

**Comment by rx4** [comment]
![fgfs-screen-041](https://user-images.githubusercontent.com/38576142/39079573-6a39d012-44d2-11e8-87f1-d17caf9dc85c.png)

**Comment by legoboyvdlp** [comment]
Could not reproduce.
Are you using Rembrandt?

**Comment by rx4** [comment]
I'm not sure what you mean. I am using windows. Windows is also Linux based.

**Comment by rx4** [comment]
I looked up Rembrandt and it gave very weird results.

**Comment by rx4** [comment]
I am using window 10 and i am using flightgear 2017.2.1

**Comment by rx4** [comment]
I have only been at 350 knots. I did not go any faster.

**Comment by legoboyvdlp** [comment]
OK.
350 knots is fairly fast, by the way. The usual cruising IAS is approx 260-300 knots (Mach 0.8 or so)
I do not have this issue, I'm not sure what is causing it.

Are you using an AMD graphics card by any chance?

**Comment by rx4** [comment]
no but the engines looked like that even when I was at the parking position.

**Comment by rx4** [comment]
That same exact thing happens with the airbus a350.

**Comment by legoboyvdlp** [comment]
This error is not seen by anyone else.

What does it look like if you enable atmospheric light scattering in View - Rendering?

**Comment by rx4** [comment]
When I install airplanes from GitHub, the only thing I do is to delete the -master part. Do you know if I did not install it properly?

**Comment by rx4** [comment]
I am waiting for a response.

**Comment by legoboyvdlp** [comment]
I think your computer has problems, almost certainly a bad graphics card. If you removed -master, that is correct.  

What does it look like if you update to FlightGear 2018.1?

**Comment by rx4** [comment]
I have another computer. I think that it may have flightgear 2017.3.1 installed. Should I try that?

**Comment by legoboyvdlp** [comment]
You should instead update your FlightGear installation to 2018.1:
http://home.flightgear.org/download/

**Comment by rx4** [comment]
Never mind. I w\WAS using rembradt I switched and it was no longer orange.

**Comment by rx4** [comment]
Problem solved. Thanks.

**Comment by rx4** [comment]
According to google, Mach .8 is 533.391 kts.

**Comment by legoboyvdlp** [comment]
That is ground speed. The speed on the displays is indicated air speed, which for Mach 0.8 at 36000 feet should be 265.8 knots.

**Comment by rx4** [comment]
Oh. AT first I thought I was too slow. That's why I sped up.
