### ISSUE TITLE
New singapore airline livery

### ISSUE THREAD

**Issue by The-flightsimgamer** [legoboyvdlp/787-9#27]
I would appreciate it if you could add the singapore airlines livery since they have ordered 20 of them and I really love the 787-9 and singapore airlines livery adds more variety to the airline liveries

Thanks,
The-flightsimgamer

**Comment by rx4** [comment]
Hello The-flightsimgamer
That's great timing for the email, I got a new computer with better
graphics just 4 hours after you sent your email. I should be able to get
this done by next week or sooner if there is a reference livery. I will try
to get that done soon.
rx4

**Comment by The-flightsimgamer** [comment]
Thank you so much!!!

**Comment by rx4** [comment]
Also, can you show me proof of the twenty orders?

**Comment by The-flightsimgamer** [comment]
https://en.wikipedia.org/wiki/Singapore_Airlines_fleet sorry was a bit late had class

**Comment by rx4** [comment]
Okay, I can see that they ordered the 787-10, not the 787-9. We'll see whether SIA does order 787-9s. For now, they didn't.

**Comment by The-flightsimgamer** [comment]
Oh then what about airlines like Vistara and American?
