### ISSUE TITLE
Stairways are not working

### ISSUE THREAD

**Issue by The-flightsimgamer** [legoboyvdlp/787-9#28]
I haven't thought much about the stairways until I tried to use it since my friend suggested a flight route for me when I try to equip the stairway it doesn't work.Please fix this issue

Thanks,
The-flightsimgamer

**Comment by legoboyvdlp** [comment]
This aircraft is unmaintained - I don't have time to fix anything, sorry.

**Comment by The-flightsimgamer** [comment]
oh its ok
