### ISSUE TITLE
Working coppy gone

### ISSUE THREAD

**Issue by CA1012** [legoboyvdlp/787-9#9]
the sub-model 787-9 is missing from the file during my latest launch of FG. i think that the last upload compromised this. Please investigate this as soon as you can.

**Comment by legoboyvdlp** [comment]
Please explain what you mean. I do not see any errors.

**Comment by legoboyvdlp** [comment]
@CA1012 -- do you want me to fix it?

**Comment by CA1012** [comment]
yes, and i noticed that  the window heat no longer works. i think there is
a missing dependency.

**Comment by legoboyvdlp** [comment]
You want me to fix it; you tell me what the problem is!

**Comment by CA1012** [comment]
i do not know. i think some depencies were lost.

**Comment by legoboyvdlp** [comment]
What's the error? What does FlightGear do?

**Comment by CA1012** [comment]
when ever i use the Virtual Co-pilot the window heat dose not want to work,
but it should be an easy fix, if not just forget it.

**Comment by legoboyvdlp** [comment]
What do you mean 'submodel missing from file'. I cannot trace the error.

**Comment by CA1012** [comment]
never mind. I just was being stupid and using the virtual copilot too
early. and can you also remove all the dependencies on the 787-8? the sound
files might need replacing but i think you can handle that right? in FG
2016 the sounds only exists in the cockpit, not externally. i hope you can
fix that.
